// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-prospects.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_prospects_default = defineTool({
  name: "list_prospects",
  title: "List prospects",
  description: "List prospects from the Prospect Master. Supports filtering by region, segment, fit category, city, and qualification status. Returns basic fields for each prospect.",
  inputSchema: {
    region_id: z.string().uuid().optional().describe("Filter by region UUID."),
    segment: z.string().optional().describe("Filter by segment slug."),
    fit_category: z.enum(["A", "B", "C", "rejected"]).optional().describe("Filter by lead fit category."),
    city: z.string().optional().describe("Filter by actual city name (case-insensitive contains)."),
    qualification_status: z.string().optional().describe("Filter by qualification_status equal match."),
    limit: z.number().int().min(1).max(200).default(50).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ region_id, segment, fit_category, city, qualification_status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("prospects").select(
      "id, company_name, actual_city, target_city, segment, region_id, fit_category, lead_score, qualification_status, website_url, phone, has_mobile_or_whatsapp"
    ).limit(limit ?? 50);
    if (region_id) q = q.eq("region_id", region_id);
    if (segment) q = q.eq("segment", segment);
    if (fit_category) q = q.eq("fit_category", fit_category);
    if (qualification_status) q = q.eq("qualification_status", qualification_status);
    if (city) q = q.ilike("actual_city", `%${city}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { count: data?.length ?? 0, rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-prospect.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_prospect_default = defineTool2({
  name: "get_prospect",
  title: "Get prospect",
  description: "Fetch a single prospect by id, including all stored fields.",
  inputSchema: {
    id: z2.string().uuid().describe("Prospect UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("prospects").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { prospect: data }
    };
  }
});

// src/lib/mcp/tools/list-regions.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_regions_default = defineTool3({
  name: "list_regions",
  title: "List regions",
  description: "List all configured sourcing regions.",
  inputSchema: {
    active_only: z3.boolean().default(true).describe("Only return active regions.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ active_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("regions").select("*").order("region_order");
    if (active_only) q = q.eq("active", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { regions: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vhsetxtzowqmwwixnxco";
var mcp_default = defineMcp({
  name: "prospect-os-mcp",
  title: "Prospect OS",
  version: "0.1.0",
  instructions: "Tools for the Prospect OS scan platform. Use `list_prospects` to browse the prospect master, `get_prospect` for a single record, and `list_regions` for the configured sourcing regions. All tools run as the signed-in user via Supabase RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_prospects_default, get_prospect_default, list_regions_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
